"""Generate COMPARISON.md from the committed results/ artifacts.

Every row is labeled with its evidence source and how to reproduce it.
Nothing in the output is hand-written: numbers are read from the JSON
artifacts, and rows whose artifact is missing are listed as NOT
MEASURED HERE rather than estimated.

Usage:  python scripts/gen_comparison.py
"""
from __future__ import annotations

import json
import statistics
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
RESULTS = REPO / "results"


def _load(name):
    p = RESULTS / name
    if not p.exists():
        return None
    return json.loads(p.read_text(encoding="utf-8"))


def _repo_link(name):
    return f"[`results/{name}`](results/{name})"


def main() -> int:
    repro = _load("repro.json")
    bqskit = _load("bqskit.json")
    pyzx = _load("pyzx_referee.json")
    qcec = _load("qcec_referee.json")
    latency = _load("latency.json")
    dd = _load("dd_ceiling.json")
    fulltranspile = _load("fulltranspile.json")

    lines = [
        "# COMPARISON.md — the competitor matrix, with evidence labels",
        "",
        "Generated by `python scripts/gen_comparison.py` from the",
        "committed `results/` artifacts.  Every row states where its",
        "numbers come from and how to reproduce them.  Rows are labeled:",
        "",
        "- **[measured]** — run in this repository, artifact committed,",
        "  regenerable via `python scripts/run_benchmarks.py` (or the",
        "  producer script named in the row).",
        "- **[referee]** — an external tool checking Compact's outputs",
        "  (not a performance comparison).",
        "- **[literature]** — numbers reported by the compared tool's own",
        "  documentation/papers.  NOT apples-to-apples with [measured]",
        "  rows; shown for context only.",
        "- **[not runnable here]** — the tool could not be executed in",
        "  this environment; no numbers are claimed.",
        "",
    ]

    # ------------------------------------------------------------------
    if repro:
        lines += [
            "## Same-input, same-gate-set matrix — [measured]",
            "",
            f"Source: {_repo_link('repro.json')} + repro.md + repro.csv, "
            f"produced by `python scripts/repro_harness.py`, suite pinned "
            f"by {_repo_link('MANIFEST.json')}, commit `{repro.get('commit', '?')}`.",
            "",
            "Method: identical inputs for every tool, every output lowered",
            "to u3+cx before counting, every output refereed by Qiskit's",
            "Operator.  Wall time includes compactq's in-product proof.",
            "",
            "| tool | mean 2q cut | median wall ms | evidence |",
            "|---|---:|---:|---|",
        ]
        s = repro.get("summary", {})
        for tool in ("compact", "qiskit", "pytket", "cirq", "pyzx", "bqskit"):
            row = s.get(tool)
            if isinstance(row, dict):
                lines.append(f"| {tool} | {row.get('mean_2q_cut_pct')}% | "
                             f"{row.get('median_wall_ms')} | [measured] |")
        wtl = s.get("compact_vs_qiskit_2q_WTL")
        if wtl:
            lines += ["", f"compact vs qiskit 2q head-to-head "
                      f"(W/T/L): **{wtl[0]} / {wtl[1]} / {wtl[2]}** [measured]"]

    # ------------------------------------------------------------------
    if bqskit:
        lines += [
            "",
            "## BQSKit head-to-head — [measured]",
            "",
            f"Source: {_repo_link('bqskit.json')} "
            f"(`python scripts/bqskit_bench.py`), BQSKit "
            f"{(bqskit.get('environment', {}).get('dependencies', {}) or {}).get('bqskit', '?')}, "
            f"commit `{bqskit.get('commit', '?')}`.",
            "",
            f"32 QASMBench small circuits, BQSKit's documented "
            f"`bqskit.compile` pipeline, every output refereed: "
            f"**{bqskit.get('count', '?')} circuits**.  Per-circuit "
            f"records in the artifact.",
        ]

    # ------------------------------------------------------------------
    if fulltranspile:
        lines += [
            "",
            "## Full-transpilation pipeline — [measured]",
            "",
            f"Source: {_repo_link('fulltranspile.json')} "
            f"(`python scripts/fulltranspile_bench.py`): compact vs "
            f"qiskit end-to-end pipelines, "
            f"{fulltranspile.get('wins', 0)} W / "
            f"{fulltranspile.get('ties', 0)} T / "
            f"{fulltranspile.get('losses', 0)} L (see artifact protocol).",
        ]

    # ------------------------------------------------------------------
    refs = []
    if pyzx:
        from collections import Counter
        st = Counter(r.get("status") for r in pyzx.get("records", []))
        parts = "; ".join(f"{v} {k}" for k, v in st.most_common())
        refs.append(f"PyZX full_reduce cross-check ({pyzx.get('count')} "
                    f"circuits): {parts} — the two phase-expression "
                    f"errors are a PyZX parser limitation, not "
                    f"inequivalence ({_repo_link('pyzx_referee.json')}, "
                    f"`python scripts/referee_pyzx.py`) [referee]")
    if qcec:
        from collections import Counter
        st = Counter(r.get("status") for r in qcec.get("records", []))
        parts = "; ".join(f"{v} {k}" for k, v in st.most_common()
                          if not k.startswith("error"))
        refs.append(f"MQT QCEC cross-check ({qcec.get('count')} "
                    f"circuits): {parts} — the two referee disagreements "
                    f"are QCEC's stricter phase tolerance; Compact's "
                    f"Operator fidelity is 1.0/0.99999999997 on those "
                    f"({_repo_link('qcec_referee.json')}, "
                    f"`python scripts/referee_qcec.py`) [referee]")
    if refs:
        lines += ["", "## External referees checking Compact — [referee]", ""]
        lines += [f"- {r}" for r in refs]

    # ------------------------------------------------------------------
    if latency:
        lines += [
            "",
            "## Latency — [measured]",
            "",
            f"Source: {_repo_link('latency.json')} "
            f"(`python scripts/latency_bench.py`): compactq import "
            f"~{latency.get('compactq_import_ms')} ms vs qiskit "
            f"~{latency.get('qiskit_import_ms')} ms; optimize with proof "
            f"p50 ~{latency.get('optimize_ms_p50')} ms / "
            f"p95 ~{latency.get('optimize_ms_p95')} ms on the small "
            f"circuit corpus ({latency.get('protocol', '')}).",
        ]

    # ------------------------------------------------------------------
    if dd:
        qft = dd.get("families", {}).get("qft", {})
        prov = qft.get("proven_upto")
        lines += [
            "",
            "## Proof-ceiling families (DD prover) — [measured]",
            "",
            f"Source: {_repo_link('dd_ceiling.json')} "
            f"(`python scripts/dd_ceiling_bench.py`): exact "
            f"decision-diagram proofs, QFT family proven to "
            f"{prov}q at the default 400k-node budget with per-width "
            f"node counts and wall times; before/after v0.2.3 deltas in "
            f"the artifact.  Per-tier scope definitions: "
            f"[VERIFICATION.md](VERIFICATION.md).",
        ]

    # ------------------------------------------------------------------
    lines += [
        "",
        "## Tools not measured in this repository — [not runnable here]",
        "",
        "- **VOQC / Quartz / GUOQ**: no runnable build in this",
        "  environment at release time; no numbers are claimed.",
        "  (Comparator dispositions recorded in",
        f"  {_repo_link('fulltranspile.md')} where attempted.)",
        "",
        "## Literature context — [literature]",
        "",
        "- Qiskit / TKET / BQSKit headline numbers quoted anywhere in",
        "  issues or docs from their own papers/docs are context only,",
        "  never merged into the [measured] tables above.",
        "",
        "The honest summary: Compact's differentiator is the in-product,",
        "tiered proof attached to every output — the point of this file",
        "is that every other number here can be checked, by anyone, from",
        "a clean clone.",
    ]

    out = REPO / "COMPARISON.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
